export enum IfoodCancellationCode {
  PROBLEMAS_DE_SISTEMA = 501,
  PEDIDO_EM_DUPLICIDADE,
  ITEM_INDISPONIVEL,
  RESTAURANTE_SEM_MOTOBOY,
  CARDÁPIO_DESATUALIZADO,
  PEDIDO_FORA_DA_ÁREA_DE_ENTREGA,
  CLIENTE_GOLPISTA_TROTE,
  FORA_DO_HORÁRIO_DO_DELIVERY,
  DIFICULDADES_INTERNAS_DO_RESTAURANTE,
  AREA_DE_RISCO,
  RESTAURANTE_ABRIRA_MAIS_TARDE,
}
